# Site settings
title: Zou Chenxuanyin
name: Zou Chenxuanyin
subtitle:  Engineer
email: zcxy@mail.ubc.ca
description: >
   Engineer
baseurl: ""
url: "https://zcxyubc.github.io/zcxyUBC"
github_username:  zcxyUBC
disqus_baseurl: "https://zcxyubc.github.io/"
disqus_shortname: https-zcxyubc-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Zou Chenxuanyin"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: zcxyUBC
    url: https://github.com/zcxyUBC
    desc: Fork me on GitHub
    share: false

  - name: ResearchGate
    icon: researchgate
    username: Chenxuanyin Zou
    url: https://www.researchgate.net/profile/Chenxuanyin-Zou
    desc: Connect with me on ResearchGate
    share: true
